---
- hosts: all
  become: true
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    - name: Install htop (idempotent)
      apt:
        name: htop
        state: present