---
- name: Install and Configure Nginx
  hosts: all
  become: true

  pre_tasks:
    - name: Set SSH user for Ubuntu systems
      set_fact:
        ansible_user: ubuntu
      when: ansible_os_family == "Debian"

    - name: Set SSH user for RedHat systems
      set_fact:
        ansible_user: ec2-user
      when: ansible_os_family == "RedHat"

  tasks:
    - name: Ensure package manager cache is updated (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure package manager cache is updated (RedHat)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on RedHat family
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on Debian family
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Create index.html
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Server Details</title></head>
          <body>
          <h1>Served from {{ ansible_hostname }}</h1>
          </body>
          </html>
        mode: '0644'

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true
